# Copyright (c) 2025 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.


jobs:
- job: code_style_validation
  displayName: Code Style Validation
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: UsePythonVersion@0
    displayName: Use Python 3.11
    inputs:
      versionSpec: 3.11

  - task: Bash@3
    displayName: Install Python dependencies
    inputs:
      targetType: inline
      script: pip install -U pre-commit

  - task: Bash@3
    displayName: Update pre-commit hook versions
    inputs:
      targetType: inline
      script: pre-commit autoupdate

  - task: Bash@3
    displayName: Validate code
    inputs:
      targetType: inline
      script: pre-commit run --all
